### ISSUE TITLE
OWASP SAMM toolbox-spreadsheet does not show correct numbers for phase specific maturity scores.

### ISSUE THREAD

**Issue by shraddhag** [owaspsamm/toolbox-spreadsheet#3]
I downloaded the excel sheet from OWASP SAMM website. Completed the self-assessment, but on Scorecard tab I don't see accurate numbers for phase specific maturity.
Also the Roadmap tab shows zero score for most the items. 

This is the url I download the spreadsheet from: https://github.com/owaspsamm/toolbox-spreadsheet/tree/main/resources
Do you have a working version of this excel?

**Comment by dkefer** [comment]
Fixed with the release 2.0.4.: https://github.com/owaspsamm/core/releases/tag/v2.0.4

**Comment by shraddhag** [comment]
@dkefer thanks for fixing the issue. I can see the phase specific maturity scores now. However, I feel the 'Roadmap' and 'Roadmap Chart' tabs are still not showing proper values. 
On the  'Roadmap Chart' tab, I was expecting phased improvement suggestions (As-Is .....To-Be) in terms of score, but most of the scores are static for all the 4 maturity phases. Due to this the pie radar charts on 'Scorecard' tab look same for all 4 phases.
Please see below screenshot. 

![image](https://user-images.githubusercontent.com/8229007/160367561-4c8a3a77-e792-4d6f-b6e5-b9ea04a1d26f.png)
